index.html, style.css
fixes #15 
I fix it by using div not using class as you said to me
But if you want this using class approach then you can say to me.
and I also close my all PR on this issue.
and also I don't delete my previous approaches. Just comment it
=> Fix: cursor pointer in nav all li action button

index.html
=> feat: add_support_option

index.html, style.css
=> changed audio controls ui

index.html
I have fixed the timestamps
this is in response to issue #32
=> Fixed the timestamps

index.html, navbar.js, style.css
Website link : https://rko0211.github.io/SpotifycloneWeb/
Fixes issue : #33 
Kindly review it ..
=> Make the navbar responsive 

index.html, style.css
Solved the responsiveness of the about page and made it attractive , changed CSS of the footer ,link sections
=> Issue #42 solved

script1.js, style.css
=> fixed song pausing issue from list

index.html, script1.js
when changing , playing,pausing a song from controls section the icons were not updating at song list
fixed it 
issue #48
=> Fixed icon bug of song list

index.html, script1.js, style.css
=> added time duration

index.html, navbar.js, style.css
Desktop view :
Mobile view :
I have tried to make the footer as it is like spotify website with little modification. Kindly review my PR. Thank you..
Resolve issue : #55
=> Update the footer

script1.js, style.css
=> song select on click song div

index.html, style.css
=> Arijit hover

index.html, style.css
added this login button with some hover effects
this button is linked with login.html file
=> added login button(#69)

home-page/home.css, home-page/home.html
Issue #72 fixed responsiveness
https://github.com/Corrupteddisk/SpotifycloneWeb/assets/121711381/2dc2262a-0687-46ff-91f0-c468b77db958
=> Added responsiveness for home page for narrow screens

About.html, home-page/home.html, index.html, main.html, style.css
linked all pages together every link is active now
and added arijits page in main.html
issue #73
=> linked all pages together

sign-in-and-login/login_form.css, sign-in-and-login/sign_up_form.css
=> made login and signup page responsive

index.html
closing Issue #108 
very small but mandatory bug fix
=> bugfixing signup and login redirection

index.html, style.css
You can see my work from here  https://rko0211.github.io/SpotifycloneWeb/
Kindly review my PR.. Thank you 
Resolve issue :  #93
=> Make the website responsive for all device

signup.css, signup.html
there was only sign-in page in this project
so i created this sign-up page
=> made a sign-up page (#91)

about/about.css, bengali/bengali.css, home-page/home.css, main.css, party/party.css, romantic/romantic.css, sad/sad.css, sign-in-and-login/login_form.css, sign-in-and-login/sign_up_form.css, style.css, support.css
Designer scrollbars are added in all the pages issue #114
=> Added designer scrollbars

index.html, style.css
Kindly review my PR..
You can see my work from here https://rko0211.github.io/SpotifycloneWeb/
Resolve issue : #81
=> Make the website responsive

about/Aboutnavbar.js, about/about.css, about/about.html, index.html
Kindly review my PR..
Reslove issue ; #111
=> Make the About Page Responsive for all device 

index.html, support.html
Support page is now linked issue #134
=> Linked the support page

sign-in-and-login/login_form.css, sign-in-and-login/login_form.html, sign-in-and-login/sign_up_form.css
Kindly review my PR under apertre24
Resolve issue : #119
=> Make the Sign in and Sign up page resopnsive for all device

bengali/bengali.html, index.html, party/party.html, romantic/romantic.html, sad/sad.html
AOS effects are added issue #137
=> AOS effects added

style.css
You can see my work from here https://rko0211.github.io/SpotifycloneWeb/
Please review my PR.
Resolve issue : #149
=> Card Responsive issue Solve

.vscode/settings.json, bengali/bengali.html, bengali/bengali.js, index.html, party/party.html, party/party.js, romantic/romantic.html, romantic/romantic.js, sad/sad.html, sad/sad.js, script1.js, style.css
=> added replay and shuffle

sign-in-and-login/login_form.css, sign-in-and-login/login_form.html, sign-in-and-login/login_form.js, sign-in-and-login/signUp.js, sign-in-and-login/sign_up_form.css, sign-in-and-login/sign_up_form.html
Example :
Kindly review my PR. Thank you.
Resolve issue :  #150
=> Sign-in Sign-up Form Validation

.vscode/settings.json, bengali/bengali.html, bengali/bengali.js, index.html, party/party.html, party/party.js, romantic/romantic.html, romantic/romantic.js, sad/sad.html, sad/sad.js, script1.js, slider.js, style.css
added scroll to top button
issue #153
=> Scroll to top

.vscode/settings.json, bengali/bengali.html, bengali/bengali.js, index.html, party/party.html, party/party.js, romantic/romantic.html, romantic/romantic.js, sad/sad.html, sad/sad.js, script1.js, style.css
modified control buttons UI
issue #144
=> Control button UI

style.css
=> Reduced size of back to top button

about/ContactFormvalidation.js, about/about.css, about/about.html, sign-in-and-login/login_form.css, sign-in-and-login/login_form.html, sign-in-and-login/login_form.js, sign-in-and-login/sign_up_form.css, sign-in-and-login/sign_up_form.html
I have added Form validation feature in the form at the same time i have updated the Contact form, 
Kindly review my PR,
Resolve issue : #169
=> Add Form validation Feature 

Scrollback.js, about/Scroll.js, about/about.css, about/about.html, main.css, main.html
=> Add Scroll back button in the pages

bengali/bengali.js, index.html, party/party.js, romantic/romantic.js, sad/sad.js, script1.js, style.css
=> added cover image at control setion

bengali/bengali.html, index.html, new_releases/new-release.html, party/party.html, romantic/romantic.html, sad/sad.html, style.css
=> Genre hover

style.css
=> added responsive medium width device

index.html, sign-in-and-login/login_form.css, sign-in-and-login/login_form.html, sign-in-and-login/sign_up_form.css, sign-in-and-login/sign_up_form.html, style.css
- Added hover effect in Sign-up page ( Google, Facebook, Apple, Phone number & login button).
- Add hover effect in login page ( Google, Facebook, Apple, Phone number & login button).
- Added hover effect on song title card.
=> Hober Effect

about/about.html
Kindly review my PR. Thank You.
Resolve issue :  #197
=> Add Links in all Navbar menu

sign-in-and-login/login_form.html, sign-in-and-login/sign_up_form.html
favicon corrected in signup and login page
=> signup login favicon corrected

bengali/bengali.html, index.html, new_releases/new-release.html, party/party.html, romantic/romantic.html, sad/sad.html, style.css
=> Added search box in all genres

bengali/bengali.html, bengali/bengali.js, new_releases/new-release.html, new_releases/new-release.js, party/party.html, party/party.js, romantic/romantic.html, romantic/romantic.js, sad/sad.html, sad/sad.js
=> Added light/dark mode in all genres

bengali/bengali.html, index.html, new_releases/new-release.html, party/party.html, romantic/romantic.html, sad/sad.html, style.css
=> made light theme better
